# version: '3.8'

# services:
#   app:
#     build:
#       context: ./backend  # Indique que le Dockerfile est dans le répertoire backend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"

version: '3.8'

services:
  app:
    build:
      context: ./backend  # Indique que le Dockerfile est dans le répertoire backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0  # Utilise l'image MySQL version 8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Mot de passe root
      MYSQL_DATABASE: ${DB_NAME}   # Nom de la base de données initiale
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Volume pour persister les données

volumes:
  mysql-data:
